### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by alber70g** [js-test-gen/js-test-gen#1]
Would it be possible to add typescript support?

**Comment by grady-lad** [comment]
@Alber70g  It should already be able to support typescript (or at least I hope!).

If you are using this lib via one of the editor plugins, you can configure the plugin to specify that you are using typescript.

Check the extensions setting in the [READMe](https://github.com/js-test-gen/js-test-gen-vscode).

**Comment by alber70g** [comment]
My bad, I didn't look thoroughly. Thanks!
